(function(definition){if(typeof exports==="object"){module.exports=definition();}else if(typeof define==="function"&&define.amd){define(definition);}else{csp_channel=definition();}})(function(){return function(){
function b(a){return function(){return a}}var n={};function q(a,c){var d=typeof c;"object"==d&&(d=c?c.constructor===Array?"array":Object.prototype.toString.call(c):"null");return Error(["No protocol method ",a," defined for type ",d,": ",c].join(""))}n.a={};n.a.h=function(a){if(a&&a.J)return a.J(a);throw q("csp.channel.MMC/cleanup",a);};n.a.e=function(a,c){if(a&&a.K)return a.K(a,c);throw q("csp.channel.ReadPort/take",a);};
n.a.put=function(a,c,d){if(a&&a.L)return a.L(a,c,d);throw q("csp.channel.WritePort/put",a);};n.a.close=function(a){if(a&&a.H)return a.H(a);throw q("csp.channel.Channel/close",a);};n.a.closed=function(a){if(a&&a.I)return a.I(a);throw q("csp.channel.Channel/closed",a);};n.a.n=function(a){if(a&&a.s)return a.s(a);throw q("csp.channel.Buffer/full",a);};n.a.remove=function(a){if(a&&a.t)return a.t(a);throw q("csp.channel.Buffer/remove",a);};
n.a.add=function(a,c){if(a&&a.r)return a.r(a,c);throw q("csp.channel.Buffer/add",a);};n.a.b=function(a){if(a&&a.u)return a.u(a);throw q("csp.channel.Handler/active",a);};n.a.c=function(a){if(a&&a.v)return a.v(a);throw q("csp.channel.Handler/commit",a);};n.a.i=function(a){if(a&&a.q)return a.q(a);throw q("csp.Core/deref",a);};n.a.count=function(a){if(a&&a.p)return a.p(a);throw q("csp.Core/count",a);};function v(a){return{q:function(){return a}}}var w={A:function(a){setTimeout(a,0)}};n.types={};
(function(a,c,d,e){a.j=function(a,c,e,d){this.d=a;this.g=c;this.buffer=e;this.closed={q:function(){return d}}};a=a.j.prototype;a.J=function(a){var e,d,l=a.d.length,h=a.g.length;for(e=0;e<h;)d=a.g[e][0],c.b(d)?e++:(a.g.splice(e,1),h--);for(e=0;e<l;)d=a.d[e],c.b(d)?e++:(a.d.splice(e,1),l--);return null};a.L=function(a,f,k){if(null===f)throw Error("Cant put null in a channel");c.h(a);if(c.closed(a))return d(null);var l,h,r,g,m=a.d.length;for(g=0;g<m;g++)if(r=a.d[g],c.b(r)&&c.b(k)){a.d.splice(g,1);l=
c.c(r);h=c.c(k);break}if(l&&h)return e.A(function(){return l(f)}),d(null);if(a.buffer&&!c.n(a.buffer)){if(c.b(k)&&c.c(k))return c.add(a.buffer,f),d(null)}else a.g.unshift([k,f]);return null};a.K=function(a,f){c.h(a);if(a.buffer&&0<c.count(a.buffer))return c.b(f)&&c.c(f)?d(c.remove(a.buffer)):null;var k,l,h,r,g,m=a.g.length;for(g=0;g<m;g++)if(r=a.g[g][0],c.b(r)&&c.b(f)){a.d.splice(g,1);k=c.c(f);l=c.c(r);h=a.g[g][1];break}if(k&&l)return e.A(l),d(h);if(c.closed(a))return c.b(f)&&c.c(f)?d(null):null;
a.d.unshift(f);return null};a.H=function(a){c.h(a);if(!c.closed(a)){a.closed={q:b(!0)};var d,k,l=a.d.length;for(k=0;k<l;k++)d=a.d[k],d=c.b(d)&&c.c(d),function(a){a&&e.A(function(){return a(null)})}(d)}return null};a.I=function(a){return!0===c.i(a.closed)}})(n.types,n.a,v,w);
(function(a,c){a.l=function(a,c){this.buffer=a;this.o=c};var d=a.l.prototype;d.s=function(a){return a.buffer.length===a.o};d.t=function(a){return a.buffer.pop()};d.r=function(a,d){if(c.n(a))throw Error("Can't add to a full buffer");return a.buffer.unshift(d)};d.p=function(a){return a.buffer.length};a.k=function(a,c){this.buffer=a;this.o=c};d=a.k.prototype;d.s=b(!1);d.t=function(a){return a.buffer.pop()};d.r=function(a,c){return a.buffer.length!==a.o?a.buffer.unshift(c):null};d.p=function(a){return a.buffer.length};
a.m=function(a,c){this.buffer=a;this.o=c};d=a.m.prototype;d.s=b(!1);d.t=function(a){return a.buffer.pop()};d.r=function(a,d){a.buffer.length===a.o&&c.remove(a);return a.buffer.unshift(d)};d.p=function(a){return a.buffer.length}})(n.types,n.a);n.f={w:function(a){return{u:b(!0),v:function(){return a}}}};
(function(a,c,d,e,B){function f(a,d){return{u:function(){return c.b(a)},v:function(){c.c(a);return d}}}function k(){var a=!0;return{u:function(){return a},v:function(){a=null;return!0}}}function l(a){var c,d,e=[];for(c=0;c<a;c++)e.push(0);for(c=1;c<a;c++)d=Math.floor(Math.random()*c),e[c]=e[d],e[d]=c;return e}function h(){return null}a.C=function(c){return new a.types.j([],[],c,null)};a.e=function(a,g,m){m=m||!0;if(a=c.e(a,d(g))){var f=c.i(a);m?g(f):e(function(){return g(f)})}return null};a.put=function(a,
g,m,f){m=m||h;f=f||!0;c.put(a,g,d(m))&&m!==h&&(f?m():e(m));return null};a.close=function(a){return c.close(a)};a.closed=function(a){return c.closed(a)};a.B=function(a,d,e){e=e||{};var h=k(),C=a.length,D=l(C),E=e.hasOwnProperty("priority"),y,t,p,s,u;for(t=0;t<C;t++)p=E?t:D[t],s=a[p],p=s.constructor===Array?s[0]:null,u=function(a,c){return a?f(h,function(){return d(null,a)}):f(h,function(a){return d(a,c)})}(p,s),(u=p?c.put(p,s[1],u):c.e(s,u))&&(y=B([c.i(u),p?p:s]));if(y)return y;e.hasOwnProperty("default")&&
c.b(h)&&c.c(h)&&B([e["default"],"default"]);return null};a.F=function(c){return new a.types.l([],c)};a.D=function(c){return new a.types.k([],c)};a.G=function(c){return new a.types.m([],c)}})(n,n.a,n.f.w,w.A,v);var x=["chan"],z=this;x[0]in z||!z.execScript||z.execScript("var "+x[0]);for(var A;x.length&&(A=x.shift());)x.length||void 0===n?z=z[A]?z[A]:z[A]={}:z[A]=n;n.a=n.a;n.impl=n.a;n.a.h=n.a.h;n.a.cleanup=n.a.h;n.a.e=n.a.e;n.a.take=n.a.e;n.a.put=n.a.put;n.a.put=n.a.put;n.a.close=n.a.close;
n.a.close=n.a.close;n.a.closed=n.a.closed;n.a.closed=n.a.closed;n.a.n=n.a.n;n.a.full=n.a.n;n.a.remove=n.a.remove;n.a.remove=n.a.remove;n.a.add=n.a.add;n.a.add=n.a.add;n.a.b=n.a.b;n.a.active=n.a.b;n.a.c=n.a.c;n.a.commit=n.a.c;n.a.i=n.a.i;n.a.deref=n.a.i;n.a.count=n.a.count;n.a.count=n.a.count;n.types=n.types;n.types=n.types;n.types.j=n.types.j;n.types.Channel=n.types.j;n.types.l=n.types.l;n.types.FixedBuffer=n.types.l;n.types.k=n.types.k;n.types.DroppingBuffer=n.types.k;n.types.m=n.types.m;
n.types.SlidingBuffer=n.types.m;n.f=n.f;n.util=n.f;n.f.w=n.f.w;n.f.handler=n.f.w;n.C=n.C;n.chan=n.C;n.e=n.e;n.take=n.e;n.put=n.put;n.put=n.put;n.close=n.close;n.close=n.close;n.closed=n.closed;n.closed=n.closed;n.B=n.B;n.alts=n.B;n.F=n.F;n.fixed_buffer=n.F;n.D=n.D;n.dropping_buffer=n.D;n.G=n.G;n.sliding_buffer=n.G;
return this.chan; }.call({});});
