(function(definition){if(typeof exports==="object"){module.exports=definition();}else if(typeof define==="function"&&define.amd){define(definition);}else{csp_channel=definition();}})(function(){return function(){
var b={};function q(a,c){var e=typeof c;"object"==e&&(e=c?c.constructor===Array?"array":Object.prototype.toString.call(c):"null");return Error(["No protocol method ",a," defined for type ",e,": ",c].join(""))}b.a={};b.a.i=function(a,c){if(a&&a.V)return a.V(a,c);throw q("csp.channel.ReadPort/take",a);};b.a.put=function(a,c,e){if(a&&a.W)return a.W(a,c,e);throw q("csp.channel.WritePort/put",a);};b.a.close=function(a){if(a&&a.T)return a.T(a);throw q("csp.channel.Channel/close",a);};
b.a.closed=function(a){if(a&&a.U)return a.U(a);throw q("csp.channel.Channel/closed",a);};b.a.v=function(a){if(a&&a.C)return a.C(a);throw q("csp.channel.Buffer/full",a);};b.a.remove=function(a){if(a&&a.D)return a.D(a);throw q("csp.channel.Buffer/remove",a);};b.a.add=function(a,c){if(a&&a.B)return a.B(a,c);throw q("csp.channel.Buffer/add",a);};b.a.f=function(a){if(a&&a.F)return a.F(a);throw q("csp.channel.Handler/active",a);};
b.a.d=function(a){if(a&&a.G)return a.G(a);throw q("csp.channel.Handler/commit",a);};b.a.n=function(a){if(a&&a.S)return a.S(a);throw q("csp.Core/deref",a);};b.a.count=function(a){if(a&&a.A)return a.A(a);throw q("csp.Core/count",a);};b.types={};
(function(a,c){function e(a,c,m,d,e){var g;for(g=0;g<e;g++)m[d+g]=a[c+g]}a.s=function(a,c,m,d){this.head=a;this.e=c;this.b=m;this.c=d};var d=a.s.prototype;d.pop=function(a){if(0===a.b)return null;var c=a.c[a.e];a.c[a.e]=null;a.e=(a.e+1)%a.c.length;a.b-=1;return c};d.unshift=function(a,c){a.c[a.head]=c;a.head=(a.head+1)%a.c.length;a.b+=1;return null};d.Q=function(a,c){a.b+1===a.c.length&&a.Y(a);a.unshift(a,c)};d.Y=function(a){var c=Array(2*a.c.length);a.e<a.head?(e(a.c,a.e,c,0,a.b),a.e=0,a.head=a.b):
a.e>a.head?(e(a.c,a.e,c,0,a.c.length-a.e),e(a.c,0,c,a.c.length-a.e,a.head),a.e=0,a.head=a.b):(a.e=0,a.head=0);a.c=c};d.R=function(a,c){for(var m;0<a.b;a++)m=a.pop(a),c(m)&&a.unshift(a,m)};a.r=function(a,c){this.buffer=a;this.w=c};d=a.r.prototype;d.C=function(a){return a.buffer.b===a.w};d.D=function(a){return a.buffer.pop(a.buffer)};d.B=function(a,d){if(c.v(a))throw Error("Can't add to a full buffer");return a.buffer.unshift(a.buffer,d)};d.A=function(a){return a.buffer.b};a.q=function(a,c){this.buffer=
a;this.w=c};d=a.q.prototype;d.C=function(){return!1};d.D=function(a){return a.buffer.pop(a.buffer)};d.B=function(a,c){return a.buffer.b!==a.w?a.buffer.unshift(a.buffer,c):null};d.A=function(a){return a.buffer.b};a.t=function(a,c){this.buffer=a;this.w=c};d=a.t.prototype;d.C=function(){return!1};d.D=function(a){return a.buffer.pop(a.buffer)};d.B=function(a,d){a.buffer.b===a.w&&c.remove(a);return a.buffer.unshift(a.buffer,d)};d.A=function(a){return a.buffer.b}})(b.types,b.a);
b.h=function(a){return new b.types.s(0,0,0,Array(a))};function s(a){return{S:function(){return a}}}
var w=function(a){function c(){e=!0;d=!1;for(var a=!0,c=0;a&&1024>c;)(a=k.pop(k))&&a(),c+=1;e=!1;!(0<k.b)||d&&e||(d=!0,t())}var e=!1,d=!1,k=a(32),t=function(){if("undefined"!==typeof MessageChannel){var a=new MessageChannel;a.port1.onmessage=function(){c()};return function(){a.port2.postMessage(0)}}return"undefined"!==typeof setImmediate?function(){setImmediate(c)}:function(){setTimeout(c,0)}}();return{L:function(a){k.Q(k,a);d&&e||(d=!0,t())}}}(b.h);
(function(a,c,e,d){function k(a){return c.f(a.l)}function t(a,c){this.l=a;this.M=c}a.p=function(a,c,d,g,p){this.j=a;this.I=c;this.m=d;this.H=g;this.buffer=p;this.closed=null};a=a.p.prototype;a.W=function(a,l,f){if(null===l)throw Error("Cant put null in a channel");if(a.closed||!c.f(f))return e(null);for(var g,p,n=!0;n;)if(n=!1,p=a.j.pop(a.j),null!==p){if(c.f(p))return g=c.d(p),c.d(f),d.L(function(){return g(l)}),e(null);n=!0}else{if(a.buffer&&!c.v(a.buffer))return c.d(f),c.add(a.buffer,l),e(null);
if(64<a.H)a.H=0,a.m.R(a.m,k);else if(a.H+=1,1024<a.m.b)throw Error("No more than 1024 pending takes on a single channel");a.m.Q(a.m,new t(f,l))}};a.V=function(a,l){if(!c.f(l))return null;if(a.buffer&&0<c.count(a.buffer))return c.d(l),e(c.remove(a.buffer));var f,g;for(f=!0;f;)if(g=a.m.pop(a.m),null!==g){f=g.l;g=g.M;if(c.f(f))return f=c.d(f),c.d(l),d.L(f),e(g);f=!0}else{if(a.closed)return c.d(l),e(null);64<a.I?(a.I=0,a.j.R(a.j,c.f)):a.I+=1;if(1024<a.j.b)throw Error("No more than 1024 pending takes on a single channel");
a.j.Q(a.j,l);return null}};a.T=function(a){if(!a.closed){a.closed=!0;for(var e,f,g=!0;g;)g=!1,e=a.j.pop(a.j),null!==e&&(c.f(e)&&(f=c.d(e),d.L(function(){return f(null)})),g=!0)}return null};a.U=function(a){return!0===a.closed}})(b.types,b.a,s,w);b.k={l:function(a){return{F:function(){return!0},G:function(){return a}}}};
(function(a,c,e,d,k){function t(a,d){return{F:function(){return c.f(a)},G:function(){c.d(a);return d}}}function m(){var a=!0;return{F:function(){return a},G:function(){a=null;return!0}}}function l(a){var c,d,e=[];for(c=0;c<a;c++)e.push(0);for(c=1;c<a;c++)d=Math.floor(Math.random()*c),e[c]=e[d],e[d]=c;return e}function f(){return null}a.u=function(c){c="number"===typeof c?0!==c?a.K(c):null:c;return new a.types.p(a.h(32),0,a.h(32),0,c,null)};a.i=function(a,p,n){n=n||!0;if(a=c.i(a,e(p))){var f=c.n(a);
n?p(f):d(function(){return p(f)})}return null};a.put=function(a,p,n,y){n=n||f;y=y||!0;c.put(a,p,e(n))&&n!==f&&(y?n():d(n));return null};a.close=function(a){return c.close(a)};a.closed=function(a){return c.closed(a)};a.J=function(a,d,e){e=e||{};var f=m(),C=a.length,D=l(C),E=e.hasOwnProperty("priority"),z,u,r,h,v;for(u=0;u<C;u++)r=E?u:D[u],h=a[r],r=h.constructor===Array?h[0]:null,v=function(a,c){return a?t(f,function(){return d(null,a)}):t(f,function(a){return d(a,c)})}(r,h),(v=r?c.put(r,h[1],v):c.i(h,
v))&&(z=k([c.n(v),r?r:h]));return z?z:e.hasOwnProperty("default")&&c.f(f)&&c.d(f)?k([e["default"],"default"]):null};a.N=function(e,f,n,l){l=l||!0;if(e=a.J(e,f,n)){var k=c.n(e);l?f(k[0],k[1]):d(function(){return f(k[0],k[1])})}return null};a.K=function(c){return new a.types.r(a.h(c),c)};a.O=function(c){return new a.types.q(a.h(c),c)};a.P=function(c){return new a.types.t(a.h(c),c)};a.timeout=function(c){var d=a.u();setTimeout(function(){a.close(d)},c);return d};a.timeout=function(c){function d(a,c){this.o=
a;this.g=c}function e(a,c,d,h){h=h||null;var f,g,k;for(g=d;0<=g;g--){for(k=!0;k;)k=!1,(f=a.forward[d])&&f.key<c&&(a=f,k=!0);h&&(h[g]=a)}return a}function f(a,c,d){var e,g=Array(d+1);for(e=0;e<=d;e++)g[e]=null;return new l(a,c,g)}function l(a,c,d){this.key=a;this.M=c;this.forward=d}var k=d.prototype;k.put=function(a,c,d){var h,g,k=Array(15);if((h=e(a.o,c,a.g,k).forward[0])&&h.key===c)h.M=d;else{for(h=0;15>h&&!(0.5<Math.random());h++);g=h;if(g>a.g){for(h=a.g+1;h<g;h++)k[h]=a.o;a.g=g}c=f(c,d,Array(g));
h=0;h<=a.g&&(a=k[h].forward,c.forward[h]=a[h],a[h]=c)}};k.remove=function(a,c){var d,h,f=Array(15),g=e(a.o,c,a.g,f).forward[0];if(g&&g.key===c)for(d=0;d<=a.g;d++)h=f[d].forward,h[d]===g&&(h[d]=g.forward[d]);else for(;0<a.g&&null===a.o.forward[a.g];)a.g-=1};k.X=function(a,c){var d,e,g,f,k=a.o;for(d=a.g;0<=d;d--){g=k;for(f=!0;f;)f=!1,(g=g.forward[d])&&(g.key>=c?e=g:f=!0);k=e?e:k}return k!==a.o?k:null};var m=new d(f(null,null,0),0);return function(d){var e,f=(new Date).valueOf()+d,h=m.X(m,f);if(h&&h.key<
f+10)return h.M;e=a.u();m.put(m,f,e);setTimeout(function(){m.remove(m,f);c.close(e)},d);return e}}(a.a);a.loop=function(){function a(){d.apply(null,[a].concat(Array.prototype.slice.call(arguments)))}var c=Array.prototype.slice.call(arguments),d=c.pop();a.apply(null,c)}})(b,b.a,b.k.l,w.L,s);var x=["chan"],A=this;x[0]in A||!A.execScript||A.execScript("var "+x[0]);for(var B;x.length&&(B=x.shift());)x.length||void 0===b?A=A[B]?A[B]:A[B]={}:A[B]=b;b.a=b.a;b.impl=b.a;b.a.i=b.a.i;b.a.take=b.a.i;
b.a.put=b.a.put;b.a.put=b.a.put;b.a.close=b.a.close;b.a.close=b.a.close;b.a.closed=b.a.closed;b.a.closed=b.a.closed;b.a.v=b.a.v;b.a.full=b.a.v;b.a.remove=b.a.remove;b.a.remove=b.a.remove;b.a.add=b.a.add;b.a.add=b.a.add;b.a.f=b.a.f;b.a.active=b.a.f;b.a.d=b.a.d;b.a.commit=b.a.d;b.a.n=b.a.n;b.a.deref=b.a.n;b.a.count=b.a.count;b.a.count=b.a.count;b.types=b.types;b.types=b.types;b.types.s=b.types.s;b.types.RingBuffer=b.types.s;b.types.r=b.types.r;b.types.FixedBuffer=b.types.r;b.types.q=b.types.q;
b.types.DroppingBuffer=b.types.q;b.types.t=b.types.t;b.types.SlidingBuffer=b.types.t;b.types.p=b.types.p;b.types.Channel=b.types.p;b.h=b.h;b.ring_buffer=b.h;b.k=b.k;b.util=b.k;b.k.l=b.k.l;b.k.handler=b.k.l;b.u=b.u;b.chan=b.u;b.i=b.i;b.take=b.i;b.put=b.put;b.put=b.put;b.close=b.close;b.close=b.close;b.closed=b.closed;b.closed=b.closed;b.J=b.J;b.do_alts=b.J;b.N=b.N;b.alts=b.N;b.K=b.K;b.fixed_buffer=b.K;b.O=b.O;b.dropping_buffer=b.O;b.P=b.P;b.sliding_buffer=b.P;b.timeout=b.timeout;b.timeout=b.timeout;
b.loop=b.loop;b.loop=b.loop;
return this.chan; }.call({});});
